services:
  bot:
    container_name: lr-bots
    restart: always
    build: 
      context: .
      dockerfile: ./prod.Dockerfile
    command: pnpm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - /usr/app/dist
    env_file:
      - .env
